import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen bg-gray-900">
          {/* Sidebar */}
          <div className="w-1/6 bg-gray-900">
            {/* Sidebar content */}
            <div className="text-white p-5">Friends</div>

            <div className="flex flex-row">
              <div className="w-full p-5">Direct messages</div>
              <div className="h-full p-5 text-white font-">+</div>
            </div>
          </div>
          {children}
          {/* Chat window */}
        </div>
      </body>
    </html>
  );
}
